### ISSUE TITLE
Tip for organization

### ISSUE THREAD

**Issue by thompsonemerson** [devspace/awesome-github-templates#1]
Hi @zenorocha,
I know it's not mandatory, but it would not better use the files of template `pull_request_template.md` and `issue_template.md` within the folder `.github`?  :bowtie: :rocket:

**Comment by zenorocha** [comment]
Define "better" ;)

It's up to you to organize your files in the way you prefer. There's no right or wrong on this one.

**Comment by thompsonemerson** [comment]
Better: Ato ou efeito de.... (em português para não perder o costume kkk)
Então, mas seria legal você poder mostrar na discrição que é possível utiliza-los tanto na raiz como dentro da pasta `.github` ;) valeu!

**Comment by zenorocha** [comment]
https://github.com/devspace/awesome-github-templates/commit/3d20923e60242c7781d5079745146480fdc1bbb7
