### ISSUE TITLE
Template links should perhaps point to a specific commit, not a branch head?

### ISSUE THREAD

**Issue by bskinn** [devspace/awesome-github-templates#15]
Linking to branch heads means that if the target projects update their templates, the documents linked to from here will also change.

Depending on the intent of the curators, linking to versions at specific commits would avoid this.

**Comment by zenorocha** [comment]
I'm ok with that, could you send a PR? Thanks!

**Comment by bskinn** [comment]
@zenorocha <nod>, I'll put one together when I get the chance.
